version: "3"
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - "8080:8080"
      - "1337:1337"
    env_file: .env
  relay:
    depends_on:
      - main
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.relay
    ports:
      - "8000:8000"
    environment:
      - SNOOZE_URL=ws://host.docker.internal:1337
