FROM python:3.9-alpine

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "relay.py"]
