FROM node:20-alpine AS node

FROM python:3.12-alpine
COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

# Verify installations
RUN python --version && node --version && npm --version

RUN apk --no-cache add curl

COPY . .

# Install any needed packages specified in requirements.txt and package.json
# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt
RUN pip install "uvicorn[standard]" websockets "pyautogen[websockets]"

EXPOSE 8080
EXPOSE 1337

CMD ["python", "main.py"]
